### PR TITLE
Introducing Metalsmith v2

### PR DESCRIPTION
**Pull request by S1SYPHOS**
- Updated package.json
  - Updated dependencies
  - Removed unused packages
- Fixed index.js
- Moved layouts/ and partials/ to root directory
  - otherwise there are endless conflicts with metalsmith-in-place
  - tried different configurations/ approaches in order to keep directory structure (eg [metalsmith-transformer](https://github.com/RobLoach/metalsmith-jstransformer)) without luck

### CODE REVIEW

**Comment by S1SYPHOS** [comment]
Needless to say, test everything before you merge this :v:

**Comment by stefanzweifel** [comment]
Thanks so much!

**Comment by S1SYPHOS** [comment]
Well, I was working on an own starter kit, and going over this was a nice byproduct :ocean:

**Comment by S1SYPHOS** [comment]
Where? I'll have a look too

**Comment by S1SYPHOS** [comment]
Hey there,
tell me where, I want to look into it too.

**Comment by stefanzweifel** [comment]
That's the current live version: https://github.com/stefanzweifel/stefanzweifel.io/blob/master/dist/posts/index.html#L48

That's the Metalsmith v2 Version:
https://github.com/S1SYPHOS/stefanzweifel.io/blob/master/dist/posts/index.html#L48

The text `Recently I discovered` is wrapped in `<p>` Tags.

**Comment by stefanzweifel** [comment]
Concerning the `p`-issue. This was probably just a bug I never noticed. 

It's also not a markdown error. By changing the `src/pages/posts.md` template, the "error" is gone :)

```diff
- <div class="lh-copy measure">{{ article.excerpt|safe }}</div>
+ <div class="lh-copy measure"><p>{{ article.excerpt|safe }}</p></div>
```

**Comment by S1SYPHOS** [comment]
So, anything else? :keyboard:

**Comment by stefanzweifel** [comment]
My previous comment might be false. The `p`-tag issue is coming from the wrong excerpt package used. (My fault to have two `excerpts` vars in `build.js`).

You removed `metalsmith-excerpts` but I used `metalsmith-better-excerpts`. Just switching these two packages fixes all issues :)

**Comment by S1SYPHOS** [comment]
Not sure I got this right: I removed `metalsmith-excerpts`, because you used `metalsmith-better-excerpts`, but you meant to say that you actually used `metalsmith-excerpts`? If so, sorry for not noticing in the first place!

**Comment by stefanzweifel** [comment]
Yeah, sorry about that. Never thought somebody would read those files :)

**Comment by S1SYPHOS** [comment]
Well, and here I am! Glad to help anyway.
Sleep tight!

**Comment by stefanzweifel** [comment]
Thanks again for the work. Merged your changes to master.

**Comment by S1SYPHOS** [comment]
You are totally welcome. I really enjoyed working with you :)

**Pull request merged**
